### ISSUE TITLE
Loss and recovery of data

### ISSUE THREAD

**Issue by ghost** [matthewwall/weewx-netatmo#3]
Hi
I appear to be loosing data, I suspect this is due to the access to the Netatmo servers.
I reduced the query period from 5 to 10 minutes, but still lost data. Going to the Netatmo site the data appears complete. Is there away to catch up and download the missing data?

Thanks
PS can you confirm your code uses the config setting for the query, as I have found fixed values in the netatmo.py code (300 seconds)

**Comment by matthewwall** [comment]
unfortunately the api for netatmo is rather ... sparse.  there is only one function, and it returns only the last data sent from the station.

does the log give you any clues about why your connections to the netatmo servers fail?

**Comment by ghost** [comment]
Hi

No, not in the current log, will turn debug on and also scan the old logs.
Any idea why they use syslog and not /var/log/weewx?
I can get the csv based histories from netatmo and I am investigating into how to load
them with the csv loader
Shame netatmo people don't allow direct usb access or sniffing.

**Comment by matthewwall** [comment]
logging defaults to /var/log/syslog because many times on new installations it is useful to see system information interspersed with weewx log entries.  for example, this tells us when there are usb issues or network issues or system restarts.

however, once you have used weewx awhile, it is often better to put weewx logs into separate file.  the weewx wiki shows how to do this.

it used to be possible to sniff netatmo traffic, and at one point we had decoded much of it.  then netatmo encrypted everything as a brute force 'fix' for their poor programming/design.  not very customer friendly!

**Comment by matthewwall** [comment]
the 0.6 driver was not catching every type of urllib network failure.  0.7 fixes this, so the driver should retry 'Connection refused' failures.

i'm not sure whether this was causing the gaps in your data.  if you're still having gaps, please reopen this issue so we can figure it out.
